# Generated by Django 2.0 on 2018-10-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funds',
            name='trader',
        ),
        migrations.DeleteModel(
            name='Global_var',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='cell_leader',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='target_month',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Funds',
        ),
        migrations.DeleteModel(
            name='Months',
        ),
        migrations.DeleteModel(
            name='Trader',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
